"""
Writer Service - Handles writing README to GitHub

This is a SERVICE (not an Agent) because it does not use LLM.
It handles:
- Validating README content before commit
- Deciding commit strategy (direct vs PR)
- Coordinating the write process

NOTE: Only LLM-powered components are called Agents.
"""

from typing import Dict, Tuple, List
from datetime import datetime


class WriterService:
    """Service that handles writing README changes to GitHub"""
    
    def __init__(self):
        """Initialize Writer Service"""
        pass
    
    def write(self, repo_full_name: str, readme_content: str,
              github_service, create_pr: bool = False,
              commit_message: str = None) -> Dict:
        """
        Write README to GitHub repository
        
        Args:
            repo_full_name: Full repository name (owner/repo)
            readme_content: README content to write
            github_service: GitHub service instance
            create_pr: Create pull request instead of direct commit
            commit_message: Custom commit message (optional)
            
        Returns:
            Result dict with success status and details
        """
        # Validate first
        is_valid, issues = self.validate(readme_content)
        if not is_valid:
            return {
                'success': False,
                'error': 'Validation failed',
                'issues': issues
            }
        
        # Default commit message
        if not commit_message:
            commit_message = "docs: Update README.md\n\nGenerated by Multi-Agent README Updater"
        
        try:
            if create_pr:
                return self._write_via_pr(repo_full_name, readme_content, github_service, commit_message)
            else:
                return self._write_direct(repo_full_name, readme_content, github_service, commit_message)
                
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }
    
    def _write_direct(self, repo_full_name: str, readme_content: str,
                      github_service, commit_message: str) -> Dict:
        """Commit directly to default branch"""
        
        result = github_service.commit_file(
            repo_full_name=repo_full_name,
            file_path='README.md',
            content=readme_content,
            commit_message=commit_message
        )
        
        return {
            'success': True,
            'method': 'direct',
            'action': result['action'],
            'commit_url': result.get('commit_url'),
            'message': f"README.md {result['action']} successfully"
        }
    
    def _write_via_pr(self, repo_full_name: str, readme_content: str,
                      github_service, commit_message: str) -> Dict:
        """Create branch and pull request"""
        
        # Generate unique branch name
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        branch_name = f"readme-update-{timestamp}"
        
        # Create branch
        github_service.create_branch(repo_full_name, branch_name)
        
        # Commit to new branch
        github_service.commit_file(
            repo_full_name=repo_full_name,
            file_path='README.md',
            content=readme_content,
            commit_message=commit_message,
            branch=branch_name
        )
        
        # Create pull request
        pr_result = github_service.create_pull_request(
            repo_full_name=repo_full_name,
            title="📝 Update README.md",
            body=self._generate_pr_body(),
            head_branch=branch_name
        )
        
        return {
            'success': True,
            'method': 'pull_request',
            'branch': branch_name,
            'pr_number': pr_result['number'],
            'pr_url': pr_result['html_url'],
            'message': f"Pull request #{pr_result['number']} created"
        }
    
    def _generate_pr_body(self) -> str:
        """Generate pull request description"""
        return """## 📝 README Update

This pull request updates the README.md with AI-generated content.

### Changes
- Improved project description
- Updated installation instructions
- Enhanced documentation structure
- Added relevant sections

### Review Checklist
- [ ] Verify project description accuracy
- [ ] Check installation steps work correctly
- [ ] Review usage examples
- [ ] Confirm no sensitive information included

---
*Generated by [Multi-Agent GitHub README Updater](https://github.com/your-repo)*
"""
    
    def validate(self, readme_content: str) -> Tuple[bool, List[str]]:
        """
        Validate README content before committing
        
        Returns:
            Tuple of (is_valid, list_of_issues)
        """
        issues = []
        
        # Check for empty content
        if not readme_content or not readme_content.strip():
            issues.append("README content is empty")
            return False, issues
        
        # Check minimum length
        if len(readme_content.strip()) < 100:
            issues.append("README is too short (less than 100 characters)")
        
        # Check for title
        lines = readme_content.strip().split('\n')
        if not lines[0].startswith('#'):
            issues.append("README should start with a title (# heading)")
        
        # Check for placeholder text (warnings, not failures)
        placeholder_patterns = ['[TODO]', '[YOUR', 'PLACEHOLDER', 'Lorem ipsum']
        for pattern in placeholder_patterns:
            if pattern.lower() in readme_content.lower():
                issues.append(f"Contains placeholder text: {pattern}")
        
        # Check recommended sections (warnings)
        content_lower = readme_content.lower()
        recommended = ['install', 'usage']
        for section in recommended:
            if section not in content_lower:
                issues.append(f"Consider adding '{section}' section")
        
        # Determine validity (only fail on critical issues)
        critical_issues = [i for i in issues if not i.startswith('Consider') and 'placeholder' not in i.lower()]
        is_valid = len(critical_issues) == 0
        
        return is_valid, issues
